### ISSUE TITLE
Is Extauth open-source or enterprise only

### ISSUE THREAD

**Issue by mjaow** [solo-io/solo-apis#25]
I saw this comments when I use the VirtualHostOptions.Extauth to build a custom_auth

```
	// Enterprise-only: Authentication configuration
	Extauth *v1.ExtAuthExtension `protobuf:"bytes,12,opt,name=extauth,proto3" json:"extauth,omitempty"`
```

Shouldn't it be open-source version configuration ? As I can see it in https://docs.solo.io/gloo-edge/master/guides/security/auth/custom_auth/

**Comment by ashleywang1** [comment]
Hello! Extauth is an enterprise-only feature, but parts of it are open-source! To see more, here are the docs: https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/
